// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SalesOnline.Console.Models
{
    public partial class Configuracion
    {
        public short Id { get; set; }
        public string Recurso { get; set; }
        public string Propiedad { get; set; }
        public string Valor { get; set; }
    }
}